### PR TITLE
fix: line breaking in small screen

### PR DESCRIPTION
**Pull request by wanglam**
### Description
Fix line wrap in small screens
Before:
image
image

After:
image
image

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by SuZhou-Joe** [comment]
Sorry but could you please add a screenshot like "Fix before" because I can not tell which part we are fixing based on the code change.

**Comment by wanglam** [comment]
> Sorry but could you please add a screenshot like "Fix before" because I can not tell which part we are fixing based on the code change.

Sure, the old screenshots added.

**Comment by SuZhou-Joe** [comment]
Nit: Not aligned.
image

**Review by SuZhou-Joe — APPROVED** [review]

**Comment by wanglam** [comment]
> nit: Not aligned. image

Good catch. Fixed. The avatar of message bubble was wrapped in small screen.

**Pull request merged**
