### PR TITLE
add 2.16 release note 

### PR DESCRIPTION
**Pull request by ruanyl**
### Description
Add release note for 2.16

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test.
- [ ] New functionality has user manual doc added.
- [ ] Commits are signed per the DCO using --signoff.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by wanglam** [comment]
Seems missed #219 in the release notes, shall we added them back? As @peterzhuamazon suggested before, I think we need to rename "Experimental Features" to "Features", is it correct? cc @raintygao

**Comment by raintygao** [comment]
> Seems missed #219 in the release notes, shall we added them back? As @peterzhuamazon suggested before, I think we need to rename "Experimental Features" to "Features", is it correct? cc @raintygao

Yes, i remembered that we don't need to add experimental in release notes any more although it's still experimental.

**Comment by ruanyl** [comment]
@wanglam @raintygao release notes updated

**Review by raintygao — APPROVED** [review]

**Comment by raintygao** [comment]
Do we need to add https://github.com/opensearch-project/dashboards-assistant/pull/219 in the notes?

**Review by wanglam — APPROVED** [review]

**Pull request merged**
