### PR TITLE
Add workflow to verify binary install into dashboards

### PR DESCRIPTION
**Pull request by derek-ho**
### Description
I have observed some issues within other plugins of issues being only caught at run time. This is because several things can go wrong during the build process, which may not be caught in a dev setup. This adds a workflow to verify that building and installing into OSD works on every PR.

Related issues:
https://github.com/opensearch-project/security-dashboards-plugin/issues/1709
https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/875
https://github.com/opensearch-project/dashboards-observability/pull/309
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5952

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test.
- [ ] New functionality has user manual doc added.
- [ ] Commits are signed per the DCO using --signoff.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by derek-ho** [comment]
Testing to see if this would have caught RC testing issue by reverting PR fix in: [6a480cd](https://github.com/opensearch-project/dashboards-assistant/pull/159/commits/6a480cd4e40618fa932efc669b5ee8f3d81793e4)

**Comment by derek-ho** [comment]
Actually not sure if this would have caught it since reading more about the issue it may be a platform specific thing that caused a different version of node to be used. @joshuali925 can you take a look at this PR regardless? I will revert the revert commit if you are in agreement that this wouldn't have caused it (although we can test it by re-running the job after OSD core no longer has issues)

**Review by joshuali925 — APPROVED** [review]
thanks. i heard those were caused by newer nodejs versions running on older platforms, i don't think `ubuntu-latest` has the issue. but i think this is good to have

**Comment by raintygao** [comment]
@derek-ho Should this change be released in 2.13?

**Review by raintygao — APPROVED** [review]

**Pull request merged**
